const defaultStore = {
  schemaVersion: 3,
  config: {
    shopName: "炖时光",
    address: "广州市番禺区东艺路意库创意十街66栋108号",
    phone: "19120670520",
    hours: "11:00-19:00",
    deliveryAreas: ["金山谷", "保利", "意库"],
    deliveryFee: 3,
    discountRate: 0.88,
    openingDiscountText: "开业活动全场 88 折，优惠至 7 月 3 日",
    saleMode: "preorder",
    paymentQrImage: "/assets/images/owner-qr.png",
    paymentTips: "请使用店长个人微信收款码付款，付款后再点击“我已付款”，店长会手动确认。",
    ownerAccessCode: "dsg2026",
  },
  products: [
    {
      id: "soup-01",
      category: "soup",
      name: "椰子百合龙骨汤",
      price: 18,
      image: "/assets/images/dish-01.jpg",
      desc: "清润顺口，适合日常滋养。",
      stock: 18,
      baseStock: 24,
    },
    {
      id: "soup-02",
      category: "soup",
      name: "五指毛桃茯苓龙骨汤",
      price: 18,
      image: "/assets/images/dish-02.jpg",
      desc: "温润耐喝，适合工作日补一口元气。",
      stock: 16,
      baseStock: 24,
    },
    {
      id: "soup-03",
      category: "soup",
      name: "黄精虫草花土鸡汤",
      price: 18,
      image: "/assets/images/dish-03.jpg",
      desc: "鲜香浓郁，想喝得更满足可以选它。",
      stock: 14,
      baseStock: 22,
    },
    {
      id: "soup-04",
      category: "soup",
      name: "西洋参石斛土鸡汤",
      price: 20,
      image: "/assets/images/dish-04.jpg",
      desc: "口感更醇厚，适合想喝点精致汤底的时候。",
      stock: 12,
      baseStock: 20,
    },
    {
      id: "soup-05",
      category: "soup",
      name: "党参陈皮龙骨汤",
      price: 20,
      image: "/assets/images/dish-07.jpg",
      desc: "陈皮回甘明显，喝起来更有层次。",
      stock: 11,
      baseStock: 18,
    },
    {
      id: "soup-06",
      category: "soup",
      name: "灵芝石斛龙骨汤",
      price: 20,
      image: "/assets/images/dish-08.jpg",
      desc: "香气稳，适合想喝得更养生一点。",
      stock: 10,
      baseStock: 18,
    },
    {
      id: "soup-07",
      category: "soup",
      name: "红萝卜汤",
      price: 15,
      image: "/assets/images/dish-10.jpg",
      desc: "清甜暖胃，属于百搭耐喝款。",
      stock: 18,
      baseStock: 24,
    },
    {
      id: "soup-08",
      category: "soup",
      name: "凉瓜汤",
      price: 15,
      image: "/assets/images/dish-09.jpg",
      desc: "清爽微苦，夏天喝会很舒服。",
      stock: 18,
      baseStock: 24,
    },
    {
      id: "soup-09",
      category: "soup",
      name: "冬瓜汤",
      price: 15,
      image: "/assets/images/dish-06.jpg",
      desc: "清润解腻，搭配面食很合适。",
      stock: 18,
      baseStock: 24,
    },
    {
      id: "noodle-01",
      category: "noodle",
      name: "葱油菠菜面",
      price: 9.9,
      image: "/assets/images/dish-09.jpg",
      desc: "清香顺口，适合想吃得轻一点。",
      stock: 20,
    },
    {
      id: "noodle-02",
      category: "noodle",
      name: "肉酱菠菜面",
      price: 12.9,
      image: "/assets/images/dish-10.jpg",
      desc: "更顶饱，适合和汤一起组成一整餐。",
      stock: 20,
    },
  ],
  materials: [
    { id: "material-box", name: "炖汤打包盒", groupKey: "packaging", groupLabel: "包材耗材", stock: 7, warningLine: 10, unit: "个" },
    { id: "material-bag", name: "打包袋", groupKey: "packaging", groupLabel: "包材耗材", stock: 26, warningLine: 10, unit: "个" },
    { id: "material-cutlery", name: "餐具", groupKey: "packaging", groupLabel: "包材耗材", stock: 40, warningLine: 15, unit: "份" },
    { id: "material-noodle-stock", name: "面条", groupKey: "kitchen", groupLabel: "厨房食材/辅料", stock: 18, warningLine: 6, unit: "份" },
    { id: "material-flour", name: "面粉", groupKey: "kitchen", groupLabel: "厨房食材/辅料", stock: 4, warningLine: 2, unit: "袋" },
    { id: "material-salt", name: "盐", groupKey: "kitchen", groupLabel: "厨房食材/辅料", stock: 5, warningLine: 2, unit: "袋" },
    { id: "material-sugar", name: "糖", groupKey: "kitchen", groupLabel: "厨房食材/辅料", stock: 4, warningLine: 2, unit: "袋" },
    { id: "material-oil", name: "油", groupKey: "kitchen", groupLabel: "厨房食材/辅料", stock: 3, warningLine: 1, unit: "桶" },
    { id: "material-seasoning", name: "调味品", groupKey: "kitchen", groupLabel: "厨房食材/辅料", stock: 6, warningLine: 2, unit: "瓶" },
  ],
  ledger: {
    "2026-06-26": {
      income: [
        { id: "income-20260626-1", amount: 168, source: "微信收款", remark: "午市外卖订单", createdAt: "2026-06-26 12:08:00" },
        { id: "income-20260626-2", amount: 56, source: "堂食收款码", remark: "到店自提", createdAt: "2026-06-26 18:16:00" },
      ],
      expense: [
        { id: "expense-20260626-1", amount: 86, category: "食材采购", remark: "早市补货", createdAt: "2026-06-26 08:05:00" },
        { id: "expense-20260626-2", amount: 18, category: "包装耗材", remark: "餐具补货", createdAt: "2026-06-26 15:12:00" },
      ],
    },
    "2026-06-25": {
      income: [{ id: "income-20260625-1", amount: 198, source: "微信收款", remark: "午高峰订单", createdAt: "2026-06-25 13:02:00" }],
      expense: [
        { id: "expense-20260625-1", amount: 112, category: "食材采购", remark: "汤料与蔬菜", createdAt: "2026-06-25 07:36:00" },
        { id: "expense-20260625-2", amount: 24, category: "其他", remark: "临时配送油费", createdAt: "2026-06-25 17:40:00" },
      ],
    },
  },
  member: {
    points: 1260,
    balance: 300,
    membership: "金卡会员",
    orderCount: 3,
    lastOrderAt: "2026/06/25 18:20:00",
    coupons: [
      { id: "coupon-88-1", title: "88 折券", desc: "全单可用", type: "discount" },
      { id: "coupon-88-2", title: "88 折券", desc: "全单可用", type: "discount" },
      { id: "coupon-soup-1", title: "炖汤兑换券", desc: "300 积分可兑换指定炖汤", type: "gift" },
    ],
  },
  orders: [
    {
      id: "CTA103",
      name: "陈小姐",
      phone: "13800000001",
      fulfillmentType: "delivery",
      address: "金山谷",
      remark: "",
      items: [
        { productId: "soup-02", productName: "五指毛桃茯苓龙骨汤", quantity: 1, price: 15.84, originalPrice: 18 },
        { productId: "noodle-01", productName: "葱油菠菜面", quantity: 1, price: 8.71, originalPrice: 9.9 },
      ],
      totals: { subtotal: 27.9, discountedSubtotal: 24.55, shipping: 3, savings: 3.35, total: 27.55 },
      status: "pending_confirm",
      createdAt: "2026/06/25 10:32:00",
    },
    {
      id: "CTA104",
      name: "李先生",
      phone: "13800000002",
      fulfillmentType: "pickup",
      address: "到店自取",
      remark: "12 点后到店",
      items: [{ productId: "soup-07", productName: "红萝卜汤", quantity: 2, price: 13.2, originalPrice: 15 }],
      totals: { subtotal: 30, discountedSubtotal: 26.4, shipping: 0, savings: 3.6, total: 26.4 },
      status: "completed",
      createdAt: "2026/06/24 18:06:00",
    },
    {
      id: "CTA105",
      name: "王女士",
      phone: "13800000003",
      fulfillmentType: "delivery",
      address: "意库",
      remark: "",
      items: [
        {
          productId: "combo:soup-03:noodle-02",
          productName: "黄精虫草花土鸡汤 + 肉酱菠菜面",
          quantity: 1,
          price: 27.19,
          originalPrice: 30.9,
          parts: [
            { productId: "soup-03", productName: "黄精虫草花土鸡汤", quantity: 1, originalPrice: 18 },
            { productId: "noodle-02", productName: "肉酱菠菜面", quantity: 1, originalPrice: 12.9 },
          ],
        },
      ],
      totals: { subtotal: 30.9, discountedSubtotal: 27.19, shipping: 3, savings: 3.71, total: 30.19 },
      status: "pending_payment",
      createdAt: "2026/06/25 11:08:00",
    },
  ],
}

module.exports = {
  defaultStore,
}
